"""Core domain exports for EPIP."""

from epip.core.candle import Candle
from epip.core.concurrency import (
    CONCURRENCY_CONTRACTS,
    ConcurrencyAware,
    ConcurrencyCapability,
    ThreadExecutionScope,
    ThreadOwnership,
    ThreadSafetyContract,
    ThreadSafetyLevel,
    concurrency_contract_for,
    declared_concurrency_contracts,
)
from epip.core.context import MarketContext
from epip.core.contracts import DecisionConsumer, EvidenceProducer, ScenarioBuilder
from epip.core.decision import Decision
from epip.core.event_bus import MAX_REENTRANT_EVENTS, EventBus, EventReentrancyError
from epip.core.events import (
    BaseEvent,
    DecisionCreated,
    DecisionRejected,
    EvidenceCreated,
    EvidenceRejected,
    ScenarioCreated,
    ScenarioRejected,
)
from epip.core.evidence import Evidence
from epip.core.hypothesis import Hypothesis
from epip.core.identity import (
    ClockProtocol,
    DeterministicClock,
    DeterministicIdGenerator,
    IdGeneratorProtocol,
    SystemClock,
    SystemIdGenerator,
)
from epip.core.integrity import (
    DataIntegrityError,
    EventIntegrityError,
    IntegrityContractError,
    IntegrityValidatable,
    MissingFieldError,
    NumericIntegrityError,
    RelationshipIntegrityError,
    SerializationIntegrityError,
    VersionIntegrityError,
)
from epip.core.kernel import Kernel, KernelResult
from epip.core.memory import (
    MEMORY_CONTRACTS,
    AllocationPolicy,
    CachePolicy,
    CleanupStrategy,
    GarbageCollectionExpectation,
    HistoryPolicy,
    MemoryAware,
    MemoryClassification,
    MemoryContract,
    MemoryFailureBehaviour,
    MemoryGrowthExpectation,
    MemoryLifecycle,
    MemoryMutability,
    MemoryOwnership,
    MemoryRegistry,
    ReleasePolicy,
    ResourceType,
    ThreadVisibility,
    declared_memory_contracts,
    get_memory_contract,
)
from epip.core.memory_audit import (
    MemoryAuditAware,
    MemoryAuditEntry,
    MemoryAuditManager,
    MemoryAuditRegistry,
    MemoryDiagnostic,
    MemoryDiagnostics,
    MemoryLeakCandidate,
    MemoryReport,
    MemorySnapshot,
    MemoryStatistics,
    MemoryViolation,
    audit_contract_coverage,
)
from epip.core.plugin_context import PluginContext
from epip.core.plugin_protocol import PluginProtocol
from epip.core.plugin_result import PluginResult
from epip.core.recovery import (
    MemoryRecoveryAware,
    MemoryRecoveryError,
    MemoryRecoveryManager,
    RecoveryAudit,
    RecoveryCheckpoint,
    RecoveryCleanupError,
    RecoveryHandle,
    RecoveryRecord,
    RecoveryScope,
    RecoveryStateError,
    RecoveryStatus,
)
from epip.core.registry import Registry
from epip.core.resource_lifecycle import (
    AutoCloseableResource,
    InvalidLifecycleTransitionError,
    LifecycleManager,
    LifecycleState,
    MemoryLifecycleAware,
    ResourceAudit,
    ResourceCleanupError,
    ResourceClosedError,
    ResourceHandle,
    ResourceLifecycle,
    ResourceLifecycleError,
    ResourceOwner,
    ResourceOwnership,
    ResourceOwnershipError,
    resource_managed_components,
)
from epip.core.retention import (
    MEMORY_RETENTION_CONTRACTS,
    CleanupTrigger,
    CompactionPolicy,
    MemoryRetentionContract,
    MemoryRetentionRegistry,
    RetentionAware,
    RetentionManager,
    RetentionPolicy,
    SnapshotPolicy,
)
from epip.core.runtime_retention import (
    RUNTIME_RETENTION_ADOPTIONS,
    RetentionAdoptionMode,
    RuntimeRetentionAdapter,
    RuntimeRetentionAdoption,
    RuntimeRetentionRegistry,
    adopt_runtime_retention,
)
from epip.core.scenario import Scenario
from epip.core.value_objects import Confidence, Price, Probability, RiskScore

__all__ = [
    "CONCURRENCY_CONTRACTS",
    "MAX_REENTRANT_EVENTS",
    "MEMORY_CONTRACTS",
    "MEMORY_RETENTION_CONTRACTS",
    "RUNTIME_RETENTION_ADOPTIONS",
    "AllocationPolicy",
    "AutoCloseableResource",
    "BaseEvent",
    "CachePolicy",
    "Candle",
    "CleanupStrategy",
    "CleanupTrigger",
    "ClockProtocol",
    "CompactionPolicy",
    "ConcurrencyAware",
    "ConcurrencyCapability",
    "Confidence",
    "DataIntegrityError",
    "Decision",
    "DecisionConsumer",
    "DecisionCreated",
    "DecisionRejected",
    "DeterministicClock",
    "DeterministicIdGenerator",
    "EventBus",
    "EventIntegrityError",
    "EventReentrancyError",
    "Evidence",
    "EvidenceCreated",
    "EvidenceProducer",
    "EvidenceRejected",
    "GarbageCollectionExpectation",
    "HistoryPolicy",
    "Hypothesis",
    "IdGeneratorProtocol",
    "IntegrityContractError",
    "IntegrityValidatable",
    "InvalidLifecycleTransitionError",
    "Kernel",
    "KernelResult",
    "LifecycleManager",
    "LifecycleState",
    "MarketContext",
    "MemoryAuditAware",
    "MemoryAuditEntry",
    "MemoryAuditManager",
    "MemoryAuditRegistry",
    "MemoryAware",
    "MemoryClassification",
    "MemoryContract",
    "MemoryDiagnostic",
    "MemoryDiagnostics",
    "MemoryFailureBehaviour",
    "MemoryGrowthExpectation",
    "MemoryLeakCandidate",
    "MemoryLifecycle",
    "MemoryLifecycleAware",
    "MemoryMutability",
    "MemoryOwnership",
    "MemoryRecoveryAware",
    "MemoryRecoveryError",
    "MemoryRecoveryManager",
    "MemoryRegistry",
    "MemoryReport",
    "MemoryRetentionContract",
    "MemoryRetentionRegistry",
    "MemorySnapshot",
    "MemoryStatistics",
    "MemoryViolation",
    "MissingFieldError",
    "NumericIntegrityError",
    "PluginContext",
    "PluginProtocol",
    "PluginResult",
    "Price",
    "Probability",
    "RecoveryAudit",
    "RecoveryCheckpoint",
    "RecoveryCleanupError",
    "RecoveryHandle",
    "RecoveryRecord",
    "RecoveryScope",
    "RecoveryStateError",
    "RecoveryStatus",
    "Registry",
    "RelationshipIntegrityError",
    "ReleasePolicy",
    "ResourceAudit",
    "ResourceCleanupError",
    "ResourceClosedError",
    "ResourceHandle",
    "ResourceLifecycle",
    "ResourceLifecycleError",
    "ResourceOwner",
    "ResourceOwnership",
    "ResourceOwnershipError",
    "ResourceType",
    "RetentionAdoptionMode",
    "RetentionAware",
    "RetentionManager",
    "RetentionPolicy",
    "RiskScore",
    "RuntimeRetentionAdapter",
    "RuntimeRetentionAdoption",
    "RuntimeRetentionRegistry",
    "Scenario",
    "ScenarioBuilder",
    "ScenarioCreated",
    "ScenarioRejected",
    "SerializationIntegrityError",
    "SnapshotPolicy",
    "SystemClock",
    "SystemIdGenerator",
    "ThreadExecutionScope",
    "ThreadOwnership",
    "ThreadSafetyContract",
    "ThreadSafetyLevel",
    "ThreadVisibility",
    "VersionIntegrityError",
    "adopt_runtime_retention",
    "audit_contract_coverage",
    "concurrency_contract_for",
    "declared_concurrency_contracts",
    "declared_memory_contracts",
    "get_memory_contract",
    "resource_managed_components",
]
