"""Core domain exports for EPIP."""

from typing import Any

from epip.core.candle import Candle
from epip.core.circuit_breaker import (
    CIRCUIT_BREAKER_CONTRACTS,
    CircuitBreaker,
    CircuitBreakerAudit,
    CircuitBreakerAware,
    CircuitBreakerConfiguration,
    CircuitBreakerContract,
    CircuitBreakerDecision,
    CircuitBreakerDiagnostics,
    CircuitBreakerRegistry,
    CircuitBreakerSnapshot,
    CircuitBreakerState,
    CircuitBreakerStatistics,
    FailureClassifier,
    FailureCounter,
    FailureIsolation,
    FailureWindow,
    SuccessCounter,
    declared_circuit_breakers,
    get_circuit_breaker_contract,
)
from epip.core.concurrency import (
    CONCURRENCY_CONTRACTS,
    ConcurrencyAware,
    ConcurrencyCapability,
    ThreadExecutionScope,
    ThreadOwnership,
    ThreadSafetyContract,
    ThreadSafetyLevel,
    concurrency_contract_for,
    declared_concurrency_contracts,
)
from epip.core.context import MarketContext
from epip.core.contracts import DecisionConsumer, EvidenceProducer, ScenarioBuilder
from epip.core.decision import Decision
from epip.core.event_bus import MAX_REENTRANT_EVENTS, EventBus, EventReentrancyError
from epip.core.events import (
    BaseEvent,
    DecisionCreated,
    DecisionRejected,
    EvidenceCreated,
    EvidenceRejected,
    ScenarioCreated,
    ScenarioRejected,
)
from epip.core.evidence import Evidence
from epip.core.exceptions import (
    EXCEPTION_REGISTRY,
    AdapterError,
    BoundaryViolationError,
    CancellationError,
    ConcurrencyError,
    ConfigurationError,
    EPIPError,
    EventBusError,
    ExceptionAware,
    ExceptionBoundary,
    ExceptionContract,
    ExceptionRegistry,
    ExceptionVisibility,
    ExecutionError,
    ExternalSystemError,
    FatalError,
    FrameworkError,
    InfrastructureError,
    InterruptedError,
    KernelError,
    MemoryError,
    NonRetryableError,
    PluginError,
    PortfolioError,
    ProviderError,
    RecoverableError,
    ReliabilityError,
    ReplayError,
    RetryableError,
    RiskError,
    RuntimeError,
    SerializationError,
    TimeoutError,
    ValidationError,
    audit_exception_hierarchy,
    declared_exception_boundaries,
    declared_exception_contracts,
    get_exception_contract,
)
from epip.core.fallback import (
    DEGRADATION_CONTRACTS,
    AvailabilityLevel,
    FallbackAction,
    FallbackAudit,
    FallbackAware,
    FallbackConfiguration,
    FallbackContext,
    FallbackContract,
    FallbackDecision,
    FallbackDiagnostics,
    FallbackPolicy,
    FallbackReason,
    FallbackRegistry,
    FallbackResult,
    FallbackRuntime,
    FallbackSnapshot,
    FallbackStatistics,
    ServiceCapability,
    declared_fallback_contracts,
    get_fallback_contract,
    transition_availability,
)
from epip.core.hypothesis import Hypothesis
from epip.core.identity import (
    ClockProtocol,
    DeterministicClock,
    DeterministicIdGenerator,
    IdGeneratorProtocol,
    SystemClock,
    SystemIdGenerator,
)
from epip.core.input_validation import (
    INPUT_VALIDATION_CONTRACTS,
    InputValidationAware,
    InputValidationContract,
    InputValidationRegistry,
    InputValidationRule,
    ValidationAudit,
    ValidationBoundary,
    ValidationCapability,
    ValidationCategory,
    ValidationDiagnostics,
    ValidationPolicy,
    ValidationResponsibility,
    ValidationSeverity,
    declared_input_validation_contracts,
    get_input_validation_contract,
)
from epip.core.integrity import (
    DataIntegrityError,
    EventIntegrityError,
    IntegrityContractError,
    IntegrityValidatable,
    MissingFieldError,
    NumericIntegrityError,
    RelationshipIntegrityError,
    SerializationIntegrityError,
    VersionIntegrityError,
)
from epip.core.kernel import Kernel, KernelResult
from epip.core.memory import (
    MEMORY_CONTRACTS,
    AllocationPolicy,
    CachePolicy,
    CleanupStrategy,
    GarbageCollectionExpectation,
    HistoryPolicy,
    MemoryAware,
    MemoryClassification,
    MemoryContract,
    MemoryFailureBehaviour,
    MemoryGrowthExpectation,
    MemoryLifecycle,
    MemoryMutability,
    MemoryOwnership,
    MemoryRegistry,
    ReleasePolicy,
    ResourceType,
    ThreadVisibility,
    declared_memory_contracts,
    get_memory_contract,
)
from epip.core.memory_audit import (
    MemoryAuditAware,
    MemoryAuditEntry,
    MemoryAuditManager,
    MemoryAuditRegistry,
    MemoryDiagnostic,
    MemoryDiagnostics,
    MemoryLeakCandidate,
    MemoryReport,
    MemorySnapshot,
    MemoryStatistics,
    MemoryViolation,
    audit_contract_coverage,
)
from epip.core.plugin_context import PluginContext
from epip.core.plugin_protocol import PluginProtocol
from epip.core.plugin_result import PluginResult
from epip.core.recovery import (
    MemoryRecoveryAware,
    MemoryRecoveryError,
    MemoryRecoveryManager,
    RecoveryAudit,
    RecoveryCheckpoint,
    RecoveryCleanupError,
    RecoveryHandle,
    RecoveryRecord,
    RecoveryScope,
    RecoveryStateError,
    RecoveryStatus,
)
from epip.core.registry import Registry
from epip.core.reliability import (
    RELIABILITY_CONTRACTS,
    FailureBoundary,
    FailureCategory,
    FailureContract,
    FailurePolicy,
    FailureResponsibility,
    FailureSeverity,
    RecoveryExpectation,
    ReliabilityAware,
    ReliabilityContract,
    ReliabilityRegistry,
    declared_reliability_contracts,
    get_reliability_contract,
)
from epip.core.reliability_audit import (
    RELIABILITY_AUDIT_REGISTRY,
    AvailabilityObservation,
    CircuitBreakerObservation,
    FailureMetric,
    FailureObservation,
    FallbackObservation,
    ReliabilityAuditAware,
    ReliabilityAuditEntry,
    ReliabilityAuditManager,
    ReliabilityAuditRegistry,
    ReliabilityAuditSnapshot,
    ReliabilityDiagnostic,
    ReliabilityDiagnostics,
    ReliabilityHistory,
    ReliabilityReport,
    ReliabilitySnapshot,
    ReliabilityStatistics,
    ReliabilityViolation,
    RetryObservation,
)
from epip.core.resource_lifecycle import (
    AutoCloseableResource,
    InvalidLifecycleTransitionError,
    LifecycleManager,
    LifecycleState,
    MemoryLifecycleAware,
    ResourceAudit,
    ResourceCleanupError,
    ResourceClosedError,
    ResourceHandle,
    ResourceLifecycle,
    ResourceLifecycleError,
    ResourceOwner,
    ResourceOwnership,
    ResourceOwnershipError,
    resource_managed_components,
)
from epip.core.retention import (
    MEMORY_RETENTION_CONTRACTS,
    CleanupTrigger,
    CompactionPolicy,
    MemoryRetentionContract,
    MemoryRetentionRegistry,
    RetentionAware,
    RetentionManager,
    RetentionPolicy,
    SnapshotPolicy,
)
from epip.core.retry import (
    RETRY_CONTRACTS,
    JitterPolicy,
    RetryAttempt,
    RetryAudit,
    RetryAware,
    RetryClassification,
    RetryCondition,
    RetryConfiguration,
    RetryContext,
    RetryContract,
    RetryDecision,
    RetryDiagnostics,
    RetryPolicy,
    RetryRegistry,
    RetryResult,
    RetryStatistics,
    RetryTrigger,
    declared_retry_contracts,
    get_retry_contract,
)
from epip.core.runtime_retention import (
    RUNTIME_RETENTION_ADOPTIONS,
    RetentionAdoptionMode,
    RuntimeRetentionAdapter,
    RuntimeRetentionAdoption,
    RuntimeRetentionRegistry,
    adopt_runtime_retention,
)
from epip.core.runtime_security import (
    RUNTIME_SECURITY_POLICIES,
    RuntimeSecurityAdapter,
    RuntimeSecurityAdoption,
    RuntimeSecurityAudit,
    RuntimeSecurityAware,
    RuntimeSecurityContext,
    RuntimeSecurityDecision,
    RuntimeSecurityDiagnostics,
    RuntimeSecurityManager,
    RuntimeSecurityPolicy,
    RuntimeSecurityRegistry,
    RuntimeSecurityResult,
    RuntimeSecuritySnapshot,
    RuntimeSecurityStatistics,
    RuntimeSecurityViolation,
    SecurityPolicyBinding,
    SecurityPolicyConfiguration,
    SecurityPolicyScope,
    declared_runtime_security_policies,
    get_runtime_security_policy,
)
from epip.core.scenario import Scenario
from epip.core.secure_failure import (
    SECURE_FAILURE_CONTRACTS,
    SecureFailureAdapter,
    SecureFailureAudit,
    SecureFailureAware,
    SecureFailureBoundary,
    SecureFailureCategory,
    SecureFailureContext,
    SecureFailureContract,
    SecureFailureDecision,
    SecureFailureDiagnostics,
    SecureFailureIncident,
    SecureFailurePolicy,
    SecureFailureRegistry,
    SecureFailureResult,
    SecureFailureSeverity,
    SecureFailureStatistics,
    declared_secure_failure_contracts,
    get_secure_failure_contract,
)
from epip.core.security import (
    SECURITY_CONTRACTS,
    SecurityAudit,
    SecurityAware,
    SecurityBoundary,
    SecurityCapability,
    SecurityClassification,
    SecurityContract,
    SecurityDiagnostics,
    SecurityLevel,
    SecurityRegistry,
    SecurityResponsibility,
    TrustLevel,
    declared_security_contracts,
    get_security_contract,
)
from epip.core.security_audit import (
    SECURITY_AUDIT_REGISTRY,
    SecurityAuditAware,
    SecurityAuditEntry,
    SecurityAuditHistory,
    SecurityAuditManager,
    SecurityAuditRegistry,
    SecurityCompliance,
    SecurityCoverage,
    SecurityDiagnostic,
    SecurityHealth,
    SecurityMetric,
    SecurityObservation,
    SecurityObservationKind,
    SecurityReport,
    SecuritySnapshot,
    SecurityStatistics,
    SecuritySummary,
    SecurityViolation,
    declared_security_audits,
    get_security_audit,
)
from epip.core.security_boundaries import (
    SECURITY_BOUNDARY_CONTRACTS,
    BoundaryAudit,
    BoundaryCapability,
    BoundaryClassification,
    BoundaryDiagnostics,
    BoundaryDirection,
    BoundaryPolicy,
    SecurityBoundaryAware,
    SecurityBoundaryContract,
    SecurityBoundaryRegistry,
    SecurityZone,
    TrustDomain,
    TrustTransition,
    declared_security_boundaries,
    get_security_boundary_contract,
)
from epip.core.value_objects import Confidence, Price, Probability, RiskScore


def __getattr__(name: str) -> Any:
    """Load optional cross-domain exports without creating import cycles."""
    if name == "decision_domain":
        from epip.decision import domain

        return domain
    if name == "evidence_engine":
        from epip.decision import evidence

        return evidence
    if name == "inference_engine":
        from epip.decision import inference

        return inference
    if name == "decision_graph":
        from epip.decision import graph

        return graph
    if name == "candidate_engine":
        from epip.decision import candidate

        return candidate
    if name == "confidence_engine":
        from epip.decision import confidence

        return confidence
    if name == "decision_engine":
        from epip.decision import decision_engine as module

        return module
    if name == "decision_validation":
        from epip.decision import validation

        return validation
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "CIRCUIT_BREAKER_CONTRACTS",
    "CONCURRENCY_CONTRACTS",
    "DEGRADATION_CONTRACTS",
    "EXCEPTION_REGISTRY",
    "INPUT_VALIDATION_CONTRACTS",
    "MAX_REENTRANT_EVENTS",
    "MEMORY_CONTRACTS",
    "MEMORY_RETENTION_CONTRACTS",
    "RELIABILITY_AUDIT_REGISTRY",
    "RELIABILITY_CONTRACTS",
    "RETRY_CONTRACTS",
    "RUNTIME_RETENTION_ADOPTIONS",
    "RUNTIME_SECURITY_POLICIES",
    "SECURE_FAILURE_CONTRACTS",
    "SECURITY_AUDIT_REGISTRY",
    "SECURITY_BOUNDARY_CONTRACTS",
    "SECURITY_CONTRACTS",
    "AdapterError",
    "AllocationPolicy",
    "AutoCloseableResource",
    "AvailabilityLevel",
    "AvailabilityObservation",
    "BaseEvent",
    "BoundaryAudit",
    "BoundaryCapability",
    "BoundaryClassification",
    "BoundaryDiagnostics",
    "BoundaryDirection",
    "BoundaryPolicy",
    "BoundaryViolationError",
    "CachePolicy",
    "CancellationError",
    "Candle",
    "CircuitBreaker",
    "CircuitBreakerAudit",
    "CircuitBreakerAware",
    "CircuitBreakerConfiguration",
    "CircuitBreakerContract",
    "CircuitBreakerDecision",
    "CircuitBreakerDiagnostics",
    "CircuitBreakerObservation",
    "CircuitBreakerRegistry",
    "CircuitBreakerSnapshot",
    "CircuitBreakerState",
    "CircuitBreakerStatistics",
    "CleanupStrategy",
    "CleanupTrigger",
    "ClockProtocol",
    "CompactionPolicy",
    "ConcurrencyAware",
    "ConcurrencyCapability",
    "ConcurrencyError",
    "Confidence",
    "ConfigurationError",
    "DataIntegrityError",
    "Decision",
    "DecisionConsumer",
    "DecisionCreated",
    "DecisionRejected",
    "DeterministicClock",
    "DeterministicIdGenerator",
    "EPIPError",
    "EventBus",
    "EventBusError",
    "EventIntegrityError",
    "EventReentrancyError",
    "Evidence",
    "EvidenceCreated",
    "EvidenceProducer",
    "EvidenceRejected",
    "ExceptionAware",
    "ExceptionBoundary",
    "ExceptionContract",
    "ExceptionRegistry",
    "ExceptionVisibility",
    "ExecutionError",
    "ExternalSystemError",
    "FailureBoundary",
    "FailureCategory",
    "FailureClassifier",
    "FailureContract",
    "FailureCounter",
    "FailureIsolation",
    "FailureMetric",
    "FailureObservation",
    "FailurePolicy",
    "FailureResponsibility",
    "FailureSeverity",
    "FailureWindow",
    "FallbackAction",
    "FallbackAudit",
    "FallbackAware",
    "FallbackConfiguration",
    "FallbackContext",
    "FallbackContract",
    "FallbackDecision",
    "FallbackDiagnostics",
    "FallbackObservation",
    "FallbackPolicy",
    "FallbackReason",
    "FallbackRegistry",
    "FallbackResult",
    "FallbackRuntime",
    "FallbackSnapshot",
    "FallbackStatistics",
    "FatalError",
    "FrameworkError",
    "GarbageCollectionExpectation",
    "HistoryPolicy",
    "Hypothesis",
    "IdGeneratorProtocol",
    "InfrastructureError",
    "InputValidationAware",
    "InputValidationContract",
    "InputValidationRegistry",
    "InputValidationRule",
    "IntegrityContractError",
    "IntegrityValidatable",
    "InterruptedError",
    "InvalidLifecycleTransitionError",
    "JitterPolicy",
    "Kernel",
    "KernelError",
    "KernelResult",
    "LifecycleManager",
    "LifecycleState",
    "MarketContext",
    "MemoryAuditAware",
    "MemoryAuditEntry",
    "MemoryAuditManager",
    "MemoryAuditRegistry",
    "MemoryAware",
    "MemoryClassification",
    "MemoryContract",
    "MemoryDiagnostic",
    "MemoryDiagnostics",
    "MemoryError",
    "MemoryFailureBehaviour",
    "MemoryGrowthExpectation",
    "MemoryLeakCandidate",
    "MemoryLifecycle",
    "MemoryLifecycleAware",
    "MemoryMutability",
    "MemoryOwnership",
    "MemoryRecoveryAware",
    "MemoryRecoveryError",
    "MemoryRecoveryManager",
    "MemoryRegistry",
    "MemoryReport",
    "MemoryRetentionContract",
    "MemoryRetentionRegistry",
    "MemorySnapshot",
    "MemoryStatistics",
    "MemoryViolation",
    "MissingFieldError",
    "NonRetryableError",
    "NumericIntegrityError",
    "PluginContext",
    "PluginError",
    "PluginProtocol",
    "PluginResult",
    "PortfolioError",
    "Price",
    "Probability",
    "ProviderError",
    "RecoverableError",
    "RecoveryAudit",
    "RecoveryCheckpoint",
    "RecoveryCleanupError",
    "RecoveryExpectation",
    "RecoveryHandle",
    "RecoveryRecord",
    "RecoveryScope",
    "RecoveryStateError",
    "RecoveryStatus",
    "Registry",
    "RelationshipIntegrityError",
    "ReleasePolicy",
    "ReliabilityAuditAware",
    "ReliabilityAuditEntry",
    "ReliabilityAuditManager",
    "ReliabilityAuditRegistry",
    "ReliabilityAuditSnapshot",
    "ReliabilityAware",
    "ReliabilityContract",
    "ReliabilityDiagnostic",
    "ReliabilityDiagnostics",
    "ReliabilityError",
    "ReliabilityHistory",
    "ReliabilityRegistry",
    "ReliabilityReport",
    "ReliabilitySnapshot",
    "ReliabilityStatistics",
    "ReliabilityViolation",
    "ReplayError",
    "ResourceAudit",
    "ResourceCleanupError",
    "ResourceClosedError",
    "ResourceHandle",
    "ResourceLifecycle",
    "ResourceLifecycleError",
    "ResourceOwner",
    "ResourceOwnership",
    "ResourceOwnershipError",
    "ResourceType",
    "RetentionAdoptionMode",
    "RetentionAware",
    "RetentionManager",
    "RetentionPolicy",
    "RetryAttempt",
    "RetryAudit",
    "RetryAware",
    "RetryClassification",
    "RetryCondition",
    "RetryConfiguration",
    "RetryContext",
    "RetryContract",
    "RetryDecision",
    "RetryDiagnostics",
    "RetryObservation",
    "RetryPolicy",
    "RetryRegistry",
    "RetryResult",
    "RetryStatistics",
    "RetryTrigger",
    "RetryableError",
    "RiskError",
    "RiskScore",
    "RuntimeError",
    "RuntimeRetentionAdapter",
    "RuntimeRetentionAdoption",
    "RuntimeRetentionRegistry",
    "RuntimeSecurityAdapter",
    "RuntimeSecurityAdoption",
    "RuntimeSecurityAudit",
    "RuntimeSecurityAware",
    "RuntimeSecurityContext",
    "RuntimeSecurityDecision",
    "RuntimeSecurityDiagnostics",
    "RuntimeSecurityManager",
    "RuntimeSecurityPolicy",
    "RuntimeSecurityRegistry",
    "RuntimeSecurityResult",
    "RuntimeSecuritySnapshot",
    "RuntimeSecurityStatistics",
    "RuntimeSecurityViolation",
    "Scenario",
    "ScenarioBuilder",
    "ScenarioCreated",
    "ScenarioRejected",
    "SecureFailureAdapter",
    "SecureFailureAudit",
    "SecureFailureAware",
    "SecureFailureBoundary",
    "SecureFailureCategory",
    "SecureFailureContext",
    "SecureFailureContract",
    "SecureFailureDecision",
    "SecureFailureDiagnostics",
    "SecureFailureIncident",
    "SecureFailurePolicy",
    "SecureFailureRegistry",
    "SecureFailureResult",
    "SecureFailureSeverity",
    "SecureFailureStatistics",
    "SecurityAudit",
    "SecurityAuditAware",
    "SecurityAuditEntry",
    "SecurityAuditHistory",
    "SecurityAuditManager",
    "SecurityAuditRegistry",
    "SecurityAware",
    "SecurityBoundary",
    "SecurityBoundaryAware",
    "SecurityBoundaryContract",
    "SecurityBoundaryRegistry",
    "SecurityCapability",
    "SecurityClassification",
    "SecurityCompliance",
    "SecurityContract",
    "SecurityCoverage",
    "SecurityDiagnostic",
    "SecurityDiagnostics",
    "SecurityHealth",
    "SecurityLevel",
    "SecurityMetric",
    "SecurityObservation",
    "SecurityObservationKind",
    "SecurityPolicyBinding",
    "SecurityPolicyConfiguration",
    "SecurityPolicyScope",
    "SecurityRegistry",
    "SecurityReport",
    "SecurityResponsibility",
    "SecuritySnapshot",
    "SecurityStatistics",
    "SecuritySummary",
    "SecurityViolation",
    "SecurityZone",
    "SerializationError",
    "SerializationIntegrityError",
    "ServiceCapability",
    "SnapshotPolicy",
    "SuccessCounter",
    "SystemClock",
    "SystemIdGenerator",
    "ThreadExecutionScope",
    "ThreadOwnership",
    "ThreadSafetyContract",
    "ThreadSafetyLevel",
    "ThreadVisibility",
    "TimeoutError",
    "TrustDomain",
    "TrustLevel",
    "TrustTransition",
    "ValidationAudit",
    "ValidationBoundary",
    "ValidationCapability",
    "ValidationCategory",
    "ValidationDiagnostics",
    "ValidationError",
    "ValidationPolicy",
    "ValidationResponsibility",
    "ValidationSeverity",
    "VersionIntegrityError",
    "adopt_runtime_retention",
    "audit_contract_coverage",
    "audit_exception_hierarchy",
    "candidate_engine",
    "concurrency_contract_for",
    "confidence_engine",
    "decision_domain",
    "decision_engine",
    "decision_graph",
    "decision_validation",
    "declared_circuit_breakers",
    "declared_concurrency_contracts",
    "declared_exception_boundaries",
    "declared_exception_contracts",
    "declared_fallback_contracts",
    "declared_input_validation_contracts",
    "declared_memory_contracts",
    "declared_reliability_contracts",
    "declared_retry_contracts",
    "declared_runtime_security_policies",
    "declared_secure_failure_contracts",
    "declared_security_audits",
    "declared_security_boundaries",
    "declared_security_contracts",
    "evidence_engine",
    "get_circuit_breaker_contract",
    "get_exception_contract",
    "get_fallback_contract",
    "get_input_validation_contract",
    "get_memory_contract",
    "get_reliability_contract",
    "get_retry_contract",
    "get_runtime_security_policy",
    "get_secure_failure_contract",
    "get_security_audit",
    "get_security_boundary_contract",
    "get_security_contract",
    "inference_engine",
    "resource_managed_components",
    "transition_availability",
]
