"""EPIP-017 Work Package A04 Evidence Semantics and Dependency Resolution.

Traceability: ADR-EPIP017-01, ADR-EPIP017-02, ADR-EPIP017-03, ADR-EPIP017-04,
ADR-EPIP017-08, ADR-EPIP017-09, ADR-EPIP017-11, and ADR-EPIP017-17;
Programme A Blueprint v1.1, Work Package A04-E00.
This package exposes immutable evidence semantic models, taxonomy axes,
dependency requirements, resolution profiles, and diagnostic codes.
"""

from epip.evidence.model import (
    AssumptionMetadata,
    CertifiedSemanticEquivalence,
    CompatibilityEffects,
    CompletenessMetadata,
    ConsumerConflictPolicy,
    DependencyType,
    DiagnosticCode,
    DiagnosticReason,
    DispositionAxis,
    EvidenceCategory,
    EvidenceClaim,
    EvidenceRequirement,
    EvidenceTaxonomy,
    EvidenceTypeDefinition,
    ExtendedRedundancyPolicy,
    IndependencePolicy,
    ProvenanceAxis,
    ProvenanceReference,
    QualityMetadata,
    ResolutionProfile,
    RetentionAxis,
    SemanticBoundary,
    SemanticIdentity,
    SemanticState,
    TemporalAxis,
    ValidityMetadata,
)

__all__ = [
    "AssumptionMetadata",
    "CertifiedSemanticEquivalence",
    "CompatibilityEffects",
    "CompletenessMetadata",
    "ConsumerConflictPolicy",
    "DependencyType",
    "DiagnosticCode",
    "DiagnosticReason",
    "DispositionAxis",
    "EvidenceCategory",
    "EvidenceClaim",
    "EvidenceRequirement",
    "EvidenceTaxonomy",
    "EvidenceTypeDefinition",
    "ExtendedRedundancyPolicy",
    "IndependencePolicy",
    "ProvenanceAxis",
    "ProvenanceReference",
    "QualityMetadata",
    "ResolutionProfile",
    "RetentionAxis",
    "SemanticBoundary",
    "SemanticIdentity",
    "SemanticState",
    "TemporalAxis",
    "ValidityMetadata",
]
